Implemented a docker build step for the target image (to avoid finalization steps)
Health-Union/snowshu pull request #86
Opened 2021-10-28 10:43 UTC by fleischer89

2021-11-01 20:56 UTC, eculicny requested changes
Since we need to use the envars to get this working, lets refactor those a little bit to move the values out of the `base_target_adapter`

2021-11-01 20:56 UTC, eculicny commented on snowshu/adapters/target_adapters/base_target_adapter.py
> +        return envars
Let's refactor the envar setup to work the way we were discussing earlier, where the keys and values are set by the more concrete type of the adapter.

Only the postgres adapters are going to care about the `PGDATA` envar.

2021-11-02 11:59 UTC, Aesthet approved these changes
Looks good to me

2021-11-02 13:22 UTC, eculicny approved these changes

2021-11-02 13:22 UTC, merged