Bug Fix: FDWs not showing with incremental build
Health-Union/snowshu pull request #94
Opened 2021-11-30 16:49 UTC by fleischer89

2021-12-01 14:36 UTC, eculicny requested changes
Unless I'm missing something, I don't see how this actually fixes the foreign data wrapper not working. 

This generates the full list of relations in graph _before_ any are removed when running an incremental build, and that set is used to create the cross database relations.

But the problem was that the newly added relations during an incremental build didn't have FDW versions added during the `enable_cross_database` function. Those newly added relations should already have been included in the `relations` set that is included on line 74 (replica_factory).

Can we add a failing test case to ensure that this is fixed

2021-12-01 14:36 UTC, eculicny commented on snowshu/core/replica/replica_factory.py
> +            not isinstance(graph.graph, Mock) else None
The application code shouldn't need to branch for testing. As `Mock` isn't used internally to snowshu, it shouldn't be handled here.

Also, if this method fixes the problem, we shouldn't have any cross db references outside of the `if self.config.source_profile.adapter.SUPPORTS_CROSS_DATABASE` block. This variable should be renamed.

2021-12-01 15:04 UTC, fleischer89 commented
> Unless I'm missing something, I don't see how this actually fixes the foreign data wrapper not working.
> 
> This generates the full list of relations in graph _before_ any are removed when running an incremental build, and that set is used to create the cross database relations.
> 
> But the problem was that the newly added relations during an incremental build didn't have FDW versions added during the `enable_cross_database` function. Those newly added relations should already have been included in the `relations` set that is included on line 74 (replica_factory).
> 
> Can we add a failing test case to ensure that this is fixed

The problem was that the database (`data_lake` in the case of the example replica) was not being passed to `enable_cross_database` for the importing of the **FDW**s so it was not able to import them that's why I went for this implementation to resolve this.

2021-12-01 15:45 UTC, eculicny commented
> The problem was that the database (`data_lake` in the case of the example replica) was not being passed to `enable_cross_database` for the importing of the **FDW**s so it was not able to import them that's why I went for this implementation to resolve this.

I was missing something, sorry about that. We should just have the `enable_cross_database` inspect the running instance to get the dbs/schemata (non-default ones) to setup FDWs for instead of expecting them to be passed as discussed.

2021-12-09 14:41 UTC, eculicny commented on tests/integration/snowflake/test_end_to_end.py
> +def test_incremental_build_with_override_image(end_to_end):
Except for this failing test, the rest of the PR looks fine.

2021-12-13 14:20 UTC, eculicny approved these changes

2021-12-13 14:20 UTC, merged