DATA-2025: Fixed PyPI deployment pipeline
Health-Union/snowshu pull request #99
Opened 2022-01-31 12:40 UTC by fleischer89

2022-02-01 01:17 UTC, eculicny commented
We should probably move the publish action to its own action yml file so that it isn't also executed on PRs and branch pushes.

Likely should have it only run when triggered manually since we don't want to create a new release for every single minor fix that happens. Alternatively, if there is an easy way to trigger a pipeline on a new tag being pushed/updated, we could use that too.

2022-02-08 20:06 UTC, eculicny requested changes

2022-02-08 20:06 UTC, eculicny commented on .github/workflows/live_deployment.yml
> +      run: cp snowshu/templates/credentials.yml tests/assets/integration/credentials.yml
I don't think it would get picked up, but we don't need to add the test credentials for publishing pipelines.

2022-02-08 20:06 UTC, eculicny commented on .github/scripts/deploy_to_pypi.sh
> +    twine upload -u __token__ -p "$TEST_PYPI_KEY" --repository testpypi dist/*
We can probably consolidate `PYPI_KEY` and `TEST_PYPI_KEY` into a single env var that is passed in the workflows. This way, we don't pass a valid production key for pypi when running test deploys.

2022-02-08 20:06 UTC, eculicny commented on requirements/base.txt
> +twine==3.7.1
Since we're using the dev docker image, we can add this requirement to `dev.txt` instead of `base.txt`

2022-02-10 21:55 UTC, eculicny requested changes
Can we consolidate the environment variables [here](https://github.com/Health-Union/snowshu/pull/99/files#r802013337) so we aren't passing around live credentials to test workflows.

2022-02-11 19:06 UTC, eculicny approved these changes

2022-02-21 13:55 UTC, Aesthet approved these changes
looks good to me

2022-02-21 14:21 UTC, merged